version: '3'

services:
    nginx:
      image: nginx
      volumes: 
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        - 80:80
        - 443:443
      depends_on:
       - frontend
       - backend
    database:
      image: postgres
      restart: always
      environment:
        POSTGRES_USER: possu
        POSTGRES_PASSWORD: password
      ports:
        - 5555:5555
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
    redis:
      image: redis
      ports:
        - 6379:6379
      volumes:
       - ./redis-data:/data
    backend:
      build: ./exercise6-backend
      ports:
        - 8000:8000     
      depends_on:
       - database
       - redis
    frontend:
      build: ./exercise5-frontend
      ports:
        - 5000:5000