version: '3'

services:
    redis:
      image: redis
      ports:
        - 6379:6379
    backend:
      build: ./exercise6-backend
      ports:
        - 8000:8000
    frontend:
      build: ./exercise5-frontend
      ports:
        - 5000:5000